#!/bin/bash
# Pulser Command Reference - Quick access to all commands

echo "🧠 Pulser Task Runner - Available Commands"
echo "=========================================="
echo ""
echo "📋 Individual Tasks:"
echo "  ./pulser-task-runner-v2.js run build-css    # Compile Tailwind CSS"
echo "  ./pulser-task-runner-v2.js run lint         # Run ESLint"
echo "  ./pulser-task-runner-v2.js run test         # Run Jest tests"
echo "  ./pulser-task-runner-v2.js run backend-qa   # Run backend QA suite"
echo "  ./pulser-task-runner-v2.js run deploy       # Deploy to Vercel"
echo ""
echo "🔗 Composite Tasks:"
echo "  ./pulser-task-runner-v2.js run ci           # build → lint → test"
echo "  ./pulser-task-runner-v2.js run qa-backend   # Backend QA only"
echo "  ./pulser-task-runner-v2.js run qa-full      # Full QA suite"
echo ""
echo "🤖 AI Tasks:"
echo "  ./pulser-task-runner-v2.js plan \"feature\"   # Generate AI plan"
echo "  ./pulser-task-runner-v2.js post-plan PR# {json} # Post to GitHub"
echo ""
echo "🔧 Utilities:"
echo "  ./pulser-task-runner-v2.js inspect          # Show configuration"
echo "  ./pulser-task-runner-v2.js status           # Show status"
echo ""
echo "💡 Tips:"
echo "  • Use PULSER_LOG_LEVEL=debug for verbose output"
echo "  • Set SUPABASE_DB_URL for database tests"
echo "  • Wrapper script: ./pulser-qa-backend.sh"
echo ""