// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment variable validation
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL) {
  throw new Error(
    '❌ Missing VITE_SUPABASE_URL environment variable. Please check your .env file and ensure VITE_SUPABASE_URL is set.'
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '❌ Missing VITE_SUPABASE_ANON_KEY environment variable. Please check your .env file and ensure VITE_SUPABASE_ANON_KEY is set.'
  );
}

// Development warnings
if (import.meta.env.DEV) {
  if ((SUPABASE_URL || []).includes('your-supabase-url')) {
    console.warn('⚠️ Using placeholder Supabase URL. Please update your .env file with your actual Supabase project URL.');
  }
  if ((SUPABASE_PUBLISHABLE_KEY || []).includes('your-anon-key')) {
    console.warn('⚠️ Using placeholder Supabase key. Please update your .env file with your actual Supabase anon key.');
  }
  console.log('✅ Supabase client initialized successfully');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
